cmake_minimum_required(VERSION 3.21)
# A duplicate data symbol can silently bind the wrong ABI before main().
function(read_symbols archive output)
    execute_process(COMMAND "${NM}" -g "${archive}"
        RESULT_VARIABLE status OUTPUT_VARIABLE listing ERROR_VARIABLE error)
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "nm failed for ${archive}: ${error}")
    endif()
    string(REPLACE "\n" ";" lines "${listing}")
    set(symbols)
    foreach(line IN LISTS lines)
        if(line MATCHES "^[0-9a-fA-F]+ +[ABCDGRSTVW] +([^ ]+)$")
            set(symbol "${CMAKE_MATCH_1}")
            if(NOT symbol MATCHES "^_*asan_globals_registered$")
                list(APPEND symbols "${symbol}")
            endif()
        endif()
    endforeach()
    if(NOT symbols)
        message(FATAL_ERROR "No defined symbols found in ${archive}")
    endif()
    set(${output} "${symbols}" PARENT_SCOPE)
endfunction()
read_symbols("${PROTOCOL}" protocol_symbols)
read_symbols("${UPSTREAM}" upstream_symbols)
foreach(symbol IN LISTS protocol_symbols)
    if(symbol IN_LIST upstream_symbols)
        message(FATAL_ERROR "DSL/upstream ABI symbol collision: ${symbol}")
    endif()
endforeach()
message(STATUS "DSL and upstream libsigrok have disjoint exported symbols")
